### ISSUE TITLE
create_memory_relationship error: error: Failed to create relationship: function ag_catalog.cypher(unknown, unknown, text[]) does not exist  code: "P0001"

### ISSUE THREAD

**Issue by grmkris** [cognitivecomputations/agi_memory#1]
tried to call the function to create new memory relationship and i get this error.. i'm prettty newbie with apache age and cypher in general, so some help would be appreciated. thank you 

`error: function cypher(unknown, unknown, text[]) does not exist`

**Comment by ehartford** [comment]
See the test code here

https://github.com/cognitivecomputations/agi_memory/blob/main/test.py#L81

**Comment by ehartford** [comment]
I fixed this, thank you for your feedback.

https://github.com/cognitivecomputations/agi_memory/blob/86ef6fd1ab7d97b4780faf84a2c8a1bf4c31274f/test.py#L1119
